dist: trusty

language: node_js

node_js:
  - node
  - lts/*
  - 8
  - 9
  - 10

cache: yarn

before_install: yarn global add istanbul codecov

script: yarn run travis

after_script: codecov

notifications:
  webhooks: https://ci-notification.limenet.xyz/dev/webhook
